---

# https://docs.docker.com/engine/install/ubuntu/
#
- name: Install docker
  hosts: all

  vars:
    pre_reqs:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    docker_packages:
      - containerd.io
      - docker-ce 
      - docker-ce-cli 

  tasks:
    - name: Install pre-reqs
      package:
        name: '{{ pre_reqs }}'
        state: present
      become: true


    - name: Install Docker apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Get Distrubution Codename
      command: lsb_release --codename --short
      register: codename
      check_mode: false
      changed_when: false

    - name: Add Docker Repository
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ codename.stdout }} stable'
        state: present
      become: true

    - name: Install Docker
      package:
        name: '{{ docker_packages }}'
        state: present
      become: true


    - name: Add user to docker group
      user:
        name: '{{ ansible_user_id }}'
        groups: docker
        append: true
      become: true
